docs/getting_started.md

To be merged at the same time as https://github.com/infracost/infracost/pull/78

chore(docs): add homebrew installation

---

docs/faq.md
docs/getting_started.md
docs/getting_support.md
docs/supported_resources.md

Related to https://github.com/infracost/infracost/pull/199

Add example

---

docs/faq.md
docs/getting_started.md
docs/integrations.md
docs/supported_resources.md
docs/usage_based_resources.md
sidebars.js

* describe the usage methods
* describe the flags and env vars
* add google resources
* split usage based content into its own page
* add gitlab CI section
* clarify a few things in the FAQ

Refactor docs

---

docs/getting_started.md

Depends on https://github.com/infracost/infracost/pull/239

Add Terragrunt options

---

docs/getting_started.md
docs/getting_support.md
docs/supported_resources.md
docs/usage_based_resources.md
docusaurus.config.js

More people seem to have it installed and other related communities (FinOps, terraform, pulumi, atlantis…) are there.

docs: switch to Slack

---

docs/getting_started.md
docs/supported_resources.md

To be merged after next infracost release goes live on homebrew

docs(supported_resources): add resources

---

docs/terraform_modules.md
sidebars.js

docs: add docs for Terraform modules

---

docs/integrations/cicd.md

Blocked by:
https://github.com/infracost/infracost/pull/611
https://github.com/infracost/infracost-jenkins/pull/2

chore: add jenkins support doc

---

blog/2021-01-04-the-prius-effect-for-cloud-costs.md
blog/2021-03-17-infracost-diff.md
docs/faq.md
docs/getting_started.md
docs/guides/advanced_usage.md
docs/integrations/cicd.md
docs/integrations/environment_variables.md
docs/integrations/infracost_api.md
docs/supported_resources.md

docs: update windows instructions

---

docs/cloud_pricing_api/self_hosted.md

Following the updates to https://github.com/infracost/helm-charts/pull/10

Update self-hosting recommended resource requests and limits

---

docs/integrations/infracost_api.md

@tim775 I copied these so users can see example responses for the other formats too, we do the same in https://www.infracost.io/docs/multi_project/report 
I'm not sure if there's a way to import/share page sections in https://docusaurus.io/docs/ - for now it's only 2 places we have these but if it becomes more we can DRY it up

docs: copy HTML and JSON tabs into this page too

---

docs/supported_resources.md

The resource is introduced here: https://github.com/infracost/infracost/pull/1112

feat(aws): add AWS Transfer Family to supported resources

---

docs/supported_resources/azure.md

Related to https://github.com/infracost/infracost/pull/1131

feat(azure): add Azure Front Door resources

---

docs/supported_resources/google.md

Related to https://github.com/infracost/infracost/pull/1140

feat(google): add Google Secret Manager resources to Supported Resources

---

docs/supported_resources/aws.md

Lines 52-54 already describe these resources.

docs: remove duplicated items in AWS paid resources list

---

docs/integrations/cicd.md

To be merged after this is released: https://gitlab.com/infracost/infracost-gitlab-ci/-/merge_requests/30

docs: add docker images section

---

docs/supported_resources/aws.md

Added in https://github.com/infracost/infracost/pull/1350

docs(aws): Add free EFS and Lambda related resources

---

docs/getting_started.md

* adds chocolatey tab
* renames windows to windows manual

docs: add windows chocolatey tab to getting started

---

docs/integrations/vscode.md
sidebars.js

docs: add VSCode Extension integration

---

blog/2022-07-05-jul-2022-update.md
docs/features/cli_commands.md
docs/features/environment_variables.md
docs/features/json_output_format.md
docs/getting_started.md
docs/infracost_cloud/get_started.md
docs/infracost_cloud/key_concepts.md

To merge when v0.10.11 is live

docs: add ‘infracost upload’ docs

---

src/css/blog.css

- makes the shadow slightly lighter

fix: makes blog card shadow lighter

---

docs/integrations/github_app.md

@vdmgolub can you plz approve and merge?

docs: fix link

---

docs/features/cli_commands.md
docs/features/environment_variables.md
docs/integrations/github_app.md

Thanks to Tymofii Dmytrenko for the workaround!

Add GitLab MR status workaround

---

docs/integrations/third_party_integrations.md

Closes https://github.com/infracost/docs/issues/363

docs: add link to Semaphore integration

---

docs/infracost_cloud/custom_price_books.md

docs: include details of custom price books

---

docs/infracost_cloud/actual_costs.md
docs/infracost_cloud/data_export.md

@tim775 plz review/tweak/merge.

docs: update data exports page

---

src/css/pricing.css

Noticed overflow issue on my mobile, here's a fix.
Before:
After:

chore: fixes card width issue on small screen

---

docs/faq.md
docs/guides/source_control_benefits.md
docs/infracost_cloud/tagging_policies.md

docs: Fix typos

---

docs/guides/source_control_benefits.md

Thanks to Dmitriy Klyuzov sharing this with the community on Slack

docs: add bitbucket step

---

docs/features/config_file.md
docs/integrations/github_app.md
docs/integrations/gitlab_app.md

@vdmgolub plz review and merge - thanks!

docs: tweak config file docs

---

docs/getting_started.md
docs/infracost_cloud/get_started.md
docs/infracost_cloud/guardrails.md
docs/infracost_cloud/tagging_policies.md
src/pages/pricing.js

@vdmgolub  can you plz review/merge? can you please approve https://github.com/infracost/docs/pull/519 too (I merged it already)?

docs: mention extra steps for CI/CD guardrail users

---

package-lock.json
package.json
src/components/Navbar.js
src/css/base.css
src/css/navbar.css

- Adding site nav change:
PS: let me know if you'd rather have one bigger PR to review, I don't mind either way.

feat: add glossary navigation

---

docs/infracost_cloud/tagging_policies.md

docs: clarify tag regex

---

docs/integrations/third_party_integrations.md

Link to the cloud-concierge docs evidencing the Infracost third-party integration.

Update third_party_integrations.md to include cloud-concierge

---

docs/infracost_cloud/tagging_policies.md

@alikhajeh1 The CLI changes are live in the github app

docs: add tag policies explanation for google user_labels

---

src/pages/glossary/finops.tsx

As per Andre's request.
Decided to use Helmet in the end 👷‍♂️.

chore: add structured data to faq

---

docs/features/terraform_modules.md

Update based on changes in https://github.com/infracost/infracost/pull/2693

docs: update `INFRACOST_TERRAFORM_SOURCE_MAP` docs with new functionality

---

src/components/Navbar.js

fix: nav alignment

---

docs/supported_resources/azure.md

adds documentation for the free resources under App Configuration service.

docs: add free azurerm_app_configuration resources

---

docs/supported_resources/google.md

This PR introduces Cloud Run paid and free resources

Add Cloud Run Resources

---

docs/infracost_cloud/finops_policies.md

@liamg can you plz review+merge?

docs: add links to regions

---

docs/features/terraform_modules.md

@liamg can you plz review and merge?

docs: add spacelift details

---

docs/features/config_file.mdx

Added a few funcs we hadn't documented

Add additional template func docs

---

docs/infracost_cloud/sso.md

So we don't have to ask a followup

Add support URL prompt in SAML setup

---

docs/infracost_cloud/jira_integration.md

Updates the jira docs to clarify how we detect jira issues.

fix: update jira docs to clarify matching

---

docs/features/config_file.mdx

* join func is available
* How to match multiple subdirectories

Add some config template docs that are helpful
