infracost/docs

docs/usage_based_resources.md

Currently it's not clear from docs that is usage based wildcard method also work with for_each resources or not.

Add wildcard for usage_based_resources with for_each

---

blog/2021-01-11-terraform-cloud-costs-directly-from-pull-request-to-management.md
docs/guides/v0.8_migration.md
docs/guides/v0.9_migration.md
docs/multi_project/report.md

Without this the glob pattern is expanded by shells so the CLI sees the first path as the flag value, followed by arguments (that are ignored)
Partly addresses #927

fix: include quotes in help text

---

src/css/docs.css

Previously the link color was white (ie. not readable) until the user
hovered over the menu item. This commit sets the link color to the
default text color which will make the heading readable even when not
hovered over.
Before:
After:

Change link color in TOC to default text color

---

docs/integrations/infracost_api.md

To add `breakdown` support to the terraform-plan-json API, I think we should rename the endpoints.  I was thinking we add `/terraform/diff` and `/terraform/breakdown`, and leave the `/terraform-json-file` around and undocumented for backwards compatibility.  What do you think?

doc: Rename terraform-json-file diff endpoint and breakdown endpoint

---

docusaurus.config.js

When the visitor of the blog or documentation has a the dark theme
enabled on their operating system the code blocks and inline code would
render with a dark text on a dark background color.
Disabling the docusaurus operating system theme detection fixes this.
Before:
After:

Fix inline code background color

---

docs/cloud_pricing_api/self_hosted.md
docs/faq.md
docs/features/cli_commands.md
docs/features/config_file.md
docs/getting_started.md
docs/guides/terraform_modules.md
docs/guides/troubleshooting.md
docs/integrations/cicd.md
docs/integrations/gitlab_ci.md
docs/support.md
docs/troubleshooting.md
sidebars.js

@aliscott only https://github.com/infracost/docs/commit/e4ac0d5d5a8997ef9de54ee7ba963813fdc6699d needs to be reviewed, I branched from master instead of 0.9.17
https://infracost.io/troubleshoot redirects to the new page. 
Related PR: https://github.com/infracost/infracost/pull/1282

docs: add troubleshooting page

---

docs/getting_started.md

Zip archives are more common in Windows than tar.gz.

docs: Change Windows latest release to a zip archive

---

docs/features/cli_commands.md
docs/getting_started.md

Removes mention of `compare-to` in `breakdown` and `output` as per change https://github.com/infracost/infracost/pull/1620

fix: remove mention of compare-to in breakdown or output

---

docusaurus.config.js
package-lock.json
package.json
src/components/PageLayout.js
src/pages/feedback/submit.js

* Adds a frontend redirect for the old feedback page. This is a back-up until the amplify redirect is setup.
* Adds a `noIndex` param to the page layout so we can exclude pages from search index.

feat: add feedback redirect

---

docs/features/cli_commands.md

The option is added here https://github.com/infracost/infracost/pull/1881.

docs: Add --exclude-cli-output option for Bitbucket comment command description

---

src/css/blog.css

Couple issues I found. This PR:
- fixes blog page top spacing on xxs screen
- fixes read more wrapping on xxs screen
Before:
After:
Before:
After:

Fix blog display issues

---

src/css/pricing.css

chore: fix pricing alignment on mobile

---

src/css/home.css

Spotted this one out in the wild 🐎
- fixes the missing gap between social media mentions and the "Download and try" CTA
Before:
After:

fix(ui): adds missing margin bottom to social media mentions

---

docs/features/cli_commands.md

@alikhajeh1 this example works but, we might want to look at the pipelines integration.  The  InfracostSetup task defaults to enableDashboard=false: 
https://github.com/infracost/infracost-azure-devops/blob/master/tasks/InfracostSetup/task.json#L53.  
Also I can't figure out how to merge prs in our demo repo it gives an `Unabled to queue Build` error 🤷

docs: Add Azure Pipelines PR status update example

---

docs/features/config_file.md
docs/guides/source_control_benefits.md
docs/infracost_cloud/tagging_policies.md
docusaurus.config.js

I like the Template, Directory Tree, Output tabs, so I think we should make sure all examples have these as well.
This page is also getting to long, so maybe we should have a separate page for the Config File Reference which includes all the function definitions.

docs: add `isDir` and `relPath`

---

src/components/FinopsSection/index.tsx
src/css/finops.css

- fix for parallax container 
Mid resolution before:
Mid resolution after:

fix: spacing in finops parallax

---

src/components/icons/Check.js

I forgot to add `#` to the the tick icon hex last time I did the refactor 🤦‍♂️
Before:
After:

fix: tick colour

---

src/css/docs.css

`@theme/TabItem` doesn't handle the content correctly.
Before:
After:

fix: add pre-wrap to pre

---

docusaurus.config.js

fix: blog search URLs

---

docs/features/config_file.md
docs/features/environment_variables.md

Documents terraform cloud variables that are used to force cloud workspace and org. See https://github.com/infracost/infracost/pull/2993 for more details.

docs: document new Terraform cloud variables

---

docs/infracost_cloud/tagging_policies.md

Adds a line to clarify the `volume_tags` functionality introduced in https://github.com/infracost/infracost/pull/3070

docs: clarify `volume_tags` behaviour

---

docs/features/config_file.md

It doesn't support single files.

docs: Update config file description about excluded_paths param

---

docs/features/terraform_modules.md

@aliscott can you please review and merge, or update the sentence to say that for GitLab module repos they still need to add HTTP or SSH creds?

docs: clarify docs

---

docs/infracost_cloud/sso.md

docs: update docs about enterprise saml groups

---

docs/infracost_cloud/sso.md
src/components/Navbar.js

@owenrumney plz review and merge

docs: tweak SSO docs

---

docs/features/usage_based_resources.md
docs/supported_resources/overview.md
docs/troubleshooting.md

These are some minor spelling and grammar tweaks for consistency (e.g. oxford comma is used everywhere else except one place).
Happy to drop any that are objectionable!

docs: spelling & grammar tweaks

---

docs/supported_resources/cloud_pricing_api.md

ModHeader has been classified as adware and malware by some third parties

docs: remove modheader mention

---

docs/integrations/third_party_integrations.md

This PR modifies the URL for the existing [Semaphore integration](https://www.infracost.io/docs/integrations/third_party_integrations/). At Semaphore, we've changed the docs engine to docusaurus and all the URLs changed. This PR fixes the single URL present in the Infracost docs.

docs: modify the URL of 3rd party integration: Semaphore

---

docs/features/config_file.mdx

- Fixed the argument order in the splitList function documentation
- The separator should be the first argument, not the second

fix: correct splitList function argument order in documentation
